# Generated by Django 5.1.4 on 2024-12-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainPurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
