# Generated by Django 5.1.4 on 2024-12-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainPurchaseDetails',
        ),
    ]
